spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mhqf123
    url: jdbc:mysql://localhost:3306/artdb?characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    name: artdb
    druid:
      filters: stat
      max-active: 1000
      initial-size: 50
      max-wait: 60000
      min-idle: 100
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from sysibm.sysdummy1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-open-prepared-statements: 20
      #druid监控配置
      stat-view-servlet.enabled: true
      web-stat-filter.url-pattern: /druid/*
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#mybatis:
#  configuration:
#    call-setters-on-nulls: true
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.itdog.entity

# swagger配置
swagger:
  enable: true

